[package]
name = "fir_filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
crossterm = "0.27.0"
thread-priority = "0.16.0"
